### ISSUE TITLE
Example Usage code is error: "The number of image tokens is 729 while the number of image given to the model is 1"

### ISSUE THREAD

**Issue by JoshonSmith** [fpgaminer/joycaption#2]
the error is blow

```
Loading checkpoint shards: 100%|█| 4/4 [00:03<00:00,  1.28it/s]
The `seen_tokens` attribute is deprecated and will be removed in v4.41. Use the `cache_position` model input instead.
Traceback (most recent call last):
    generate_ids = llava_model.generate(input_ids=input_ids.to('cuda'), pixel_values=pixel_values.to('cuda'), attention_mask=attention_mask.to('cuda'), max_new_tokens=300, do_sample=True, suppress_tokens=None, use_cache=True)[0]
  File "python3.10/site-packages/torch/utils/_contextlib.py", line 116, in decorate_context
    return func(*args, **kwargs)
  File "python3.10/site-packages/transformers/generation/utils.py", line 2024, in generate
    result = self._sample(
  File "python3.10/site-packages/transformers/generation/utils.py", line 2982, in _sample
    outputs = self(**model_inputs, return_dict=True)
  File "python3.10/site-packages/torch/nn/modules/module.py", line 1553, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "python3.10/site-packages/torch/nn/modules/module.py", line 1562, in _call_impl
    return forward_call(*args, **kwargs)
  File "python3.10/site-packages/transformers/models/llava/modeling_llava.py", line 443, in forward
    inputs_embeds, attention_mask, labels, position_ids = self._merge_input_ids_with_image_features(
  File "/python3.10/site-packages/transformers/models/llava/modeling_llava.py", line 339, in _merge_input_ids_with_image_features
    raise ValueError(
ValueError: The input provided to the model are wrong. The number of image tokens is 729 while the number of image given to the model is 1. This prevents correct indexing and breaks batch generation.

```

the env is:

```
tokenizers                0.19.1
toml                      0.10.2
tomli                     2.0.1
tomlkit                   0.12.0
toolz                     0.12.1
torch                     2.4.0+cu124
torchdiffeq               0.2.4
torchmetrics              1.4.1
torchsde                  0.2.6
torchvision               0.19.0+cu124
tqdm                      4.66.5
trampoline                0.1.2
transformers              4.44.0
triton                    3.0.0
```

**Comment by fpgaminer** [comment]
I think you need transformers 4.45 for it to work correctly.

**Comment by JoshonSmith** [comment]
transformers 4.45 is work!

**Comment by feffy380** [comment]
> I think you need transformers 4.45 for it to work correctly.

Could this be added to a requirements.txt?
